### ISSUE TITLE
npm run build giving error.

### ISSUE THREAD

**Issue by ddnatu** [ngx-rocket/starter-kit#4]
I build two separate components for my project purpose, these are working fine on development environment but as soon as I bundle them using npm run build, many errors pop up on the console saying new Module title does not exist on type 'Object' and so forth.
Please help!

**Comment by sinedied** [comment]
`npm run build` use [AoT compilation](https://angular.io/docs/ts/latest/cookbook/aot-compiler.html#!#aot-jit), in opposition to the JIT compiler used in development mode

In order to build your app using AoT for production, there is few things that needs special care, like using arrow function for providers instead of factory functions for example: https://github.com/angular/angular/issues/11262

See [this article](https://medium.com/@isaacplmann/making-your-angular-2-library-statically-analyzable-for-aot-e1c6f3ebedd5) that explains how to make your code compatible with AoT.

It's hard to give help on your specific case if we don't know the exact errors you're having.

**Comment by sinedied** [comment]
I'm closing this issue in the lack of feedback.
